version: '3.1'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '62001:6379'

  postgres:
    image: 'postgres:15-alpine'
    working_dir: /app
    volumes:
      - '.:/app'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=WaterDrop2023
      - POSTGRES_DB=dog_db
    ports:
      - '62014:5432'

  php-fpm:
    build: docker/php-fpm
    working_dir: /app
    volumes:
      - '.:/app'
      - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'

  webserver:
    image: 'nginx:alpine'
    working_dir: /app
    depends_on:
      - php-fpm
    links:
      - php-fpm
    volumes:
      - '.:/app'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '62000:80'

  worker:
    build: docker/worker
    working_dir: /app
    depends_on:
      - redis
      - postgres
      - php-fpm
    volumes:
      - '.:/app'
      - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'